branches:
  only:
  - master
skip_tags: true
build: off
test: off
deploy:
- provider: FTP
  host:
    secure: H6bRvr6FiP3wyFSKBZGFXW9rk7ie1AinE/L3ehC0pzs=
  protocol: sftp
  username:
    secure: 7MrkC4KDGY8tZNyNy5/7/zxP7RJMcNVmFJB8xfcQ3rk=
  password:
    secure: MZdYF7ohMP31C1eHkYWQeQ==
